#!/usr/bin/env bash
#
# ssh-agents-ensure - Ensure configured agents are running

set -eu -o pipefail

agents_dir="${HOME}/.ssh/keycutter/agents"

for agent_dir in "$agents_dir"/*; do
    if [[ -d "$agent_dir" ]]; then
        socket="$agent_dir/ssh-agent.socket"
        if [[ ! -S "$socket" ]] || ! SSH_AUTH_SOCK="$socket" ssh-add -l >/dev/null 2>&1; then
            rm -f "$socket"
            ssh-agent -a "$socket" >/dev/null
        fi
        export SSH_AUTH_SOCK="$socket"
        ssh-add -D
        for key in "$agent_dir"/keys/*@{${KEYCUTTER_ORIGIN:-$(hostname -s)},keyring}; do
            [[ -f "$key" && "$key" != *.pub ]] && ssh-add "$key"
        done
    fi
done
