#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail
set -x

# ssh-agent-ensure - Ensure correct ssh-agent is started with correct keys.

host="${1:-}"

export SSH_AUTH_SOCK=$(ssh -G "$host" 2>/dev/null | awk '/^identityagent / {print $2}')
[[ -n $SSH_AUTH_SOCK ]] || exit 0

agent_dir=$(dirname "$SSH_AUTH_SOCK")

if [[ ! -S "$SSH_AUTH_SOCK" ]] || ! ssh-add -l &>/dev/null; then
    rm -f "$SSH_AUTH_SOCK"
    ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
fi

ssh-add -D 2> /dev/null

shopt -s nullglob
for key in "$agent_dir"/keys/*@${KEYCUTTER_ORIGIN:-"$(hostname -s)"}; do
    if [[ -f "$key" && "$key" != *.pub ]]; then
        ssh-add "$key" &>/dev/null
    fi
done
shopt -u nullglob
